### ISSUE TITLE
Arrow and .bam file compatibility

### ISSUE THREAD

**Issue by peterthorpe5** [PacificBiosciences/GenomicConsensus#123]
Dear PacificBiosciences,

I am trying to (test) run Arrow. BLASR (used to produce the .bam file) has been mapping my reads for over a week (still running). So, I tried some faster mappers (minimap1 and 2, and minialign). The resulting sam files were sorted and indexed as .bam files. If I feed these bam files into Arrow I consistently get the following error (see below). The Arrow we are using is a singularity image build on smrt-tools 5.1.0. I have read (https://flowersoftheocean.wordpress.com/2018/04/16/polishing-pacbio-assemblies-with-arrow-and-pilon/) that Arrow will only work with bam files generated by BLASR. Is this correct?

My question:

1)	Can Arrow take .bam files generated by other programs? If not, what needs to be altered?
2)	The bam file name, is a positional argument. Is my command correct. 
3)	Can you see anything else I have done wrong?

Regards,

Peter Thorpe

$ THREADS=4
$ PREFIX=species_mini2
$ ITERNUM=1

$ singularity run --app arrow /mnt/apps/singularity/images/smrt-tools/5.1.0/smrt-tools.img  sorted_mini2.bam  --diploid --log-file miniarrow.log -j $THREADS --referenceFilename curated.fasta -o ${PREFIX}.arrow${ITERNUM}.fasta -o ${PREFIX}.arrow${ITERNUM}.gff -o ${PREFIX}.arrow${ITERNUM}.fastq
'pb'
Traceback (most recent call last):
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 383, in args_runner
    return tr.main()
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 2723, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 1987, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 477, in __init__
    self.updateCounts()
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 2541, in updateCounts
    self.assertIndexed()
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 2371, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 1944, in _assertIndexed
    self._openFiles()
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/dataset/DataSetIO.py", line 2068, in _openFiles
    resource = IndexedBamReader(location)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/align/BamIO.py", line 388, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._checkFileCompatibility()
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/align/BamIO.py", line 188, in _checkFileCompatibility
    checkedVersion = self.version
  File "/opt/pacbio/smrtlink/install/smrtlink-release_5.1.0.26412/bundles/smrttools/install/smrttools-release_5.1.0.26366/private/thirdparty/python/python_2.7.9/site-packages/pbcore/io/align/BamIO.py", line 274, in version
    return self.peer.header["HD"]["pb"]
KeyError: 'pb'

**Comment by pb-dseifert** [comment]
Your file is not a valid PB BAM file. Using anything but BLASR is unlikely to give you a valid PB BAM. Try `pbbamify` from the `pbbam` package on Bioconda if you like.
