### ISSUE TITLE
Error after conda installation

### ISSUE THREAD

**Issue by mvollger** [PacificBiosciences/GenomicConsensus#124]
Hello,

I am working with a conda installation and was hoping I could get help here. If this is the wrong place please let me know who I might contact.

genomicconsensus installs without error but then executing quiver in anyway it always gives the same argparse error.
`conda install -c bioconda genomicconsensus `
I have tried installing with several versions of gcc and python and nothing has changed. 

Here is my error:
```
=> python --version
Python 2.7.3 :: Continuum Analytics, Inc.
=> quiver
Traceback (most recent call last):
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/bin/variantCaller", line 5, in <module>
    sys.exit(main())
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/site-packages/GenomicConsensus/main.py", line 408, in main
    parser=get_parser(),
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/site-packages/GenomicConsensus/options.py", line 141, in get_parser
    add_options_to_argument_parser(p.arg_parser.parser)
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/site-packages/GenomicConsensus/options.py", line 305, in add_options_to_argument_parser
    help="Set the verbosity level.")
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/net/eichler/vol2/home/mvollger/anaconda3/envs/quiver2/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -v/--verbose: conflicting option string(s): --verbose
```

Any help would be appreciated, thanks!

**Comment by pb-dseifert** [comment]
The version of genomicconsensus in bioconda is not maintained by PacBio. I will be adding an offically supported version soon.

**Comment by mvollger** [comment]
I see, I am excited to hear that there are plans to officially support a conda install.

Not to press you too much, but is there any timeline on that? I have had trouble installing quiver in the past so I'd be happy to put if off for a few weeks if a conda version is about to come out. 

Thanks!

**Comment by pb-dseifert** [comment]
In general we do not give ETAs and say that things are done "when they're done". In this case, GC will be on bioconda in the next few weeks.

**Comment by mvollger** [comment]
Thanks for making an exception and giving me an estimate. I will put off trying to make my own build for the time being. 

Will you update this thread when it is released, or is there another place I should check for updates on the release? 

Thanks!

**Comment by mhsieh** [comment]
I will keep the thread updated.

**Comment by mvollger** [comment]
Great, thanks again!

**Comment by pb-dseifert** [comment]
This took a bit longer than I had anticipated, but GenomicConsensus should finally work in bioconda now, both for RSII and Sequel datasets, I hope you find it useful:

    conda install -c bioconda genomicconsensus

**Comment by mvollger** [comment]
Thanks so much. I’ll try it out right now.

**Comment by pb-dseifert** [comment]
I think we are done here.
