### ISSUE TITLE
Old Quiver/New Error -- Conda installation attempts failing

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/GenomicConsensus#126]
Hi,

In 2015 - I installed quiver successfully after a lot of trials. Quiver is a great program and I need it once again to repeat the analyses I did back then.

I used to have no trouble running it. It has been a year or two since I ran it -- but now when I do, I get this error:
```
Traceback (most recent call last):
  File "/users/jurban/software/localpy/bin/variantCaller", line 5, in <module>
    sys.exit(main())
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 402, in main
    parser=get_parser(),
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/options.py", line 148, in get_parser
    add_options_to_argument_parser(p.arg_parser.parser)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/options.py", line 312, in add_options_to_argument_parser
    help="Set the verbosity level.")
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/gpfs/runtime/opt/python/2.7.3/lib/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -v/--verbose: conflicting option string(s): --verbose
```

I am not entirely sure what changed in my environment that has lead to it now not working. Therefore, I was happy to see that GenomicConsensus could not be installed via conda. Among other ways, I tried:
```
conda create --force -n quiver -c bioconda genomicconsensus
conda activate quiver
quiver -h
```

This throws the following error:
```
Traceback (most recent call last):
  File "/users/jurban/data/software/conda/anaconda3/envs/quiver/bin/variantCaller", line 3, in <module>
    from GenomicConsensus.main import main
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 40, in <module>
    from pbcommand.utils import setup_log
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/utils.py", line 15, in <module>
    from pbcommand.models import FileTypes, DataSetMetaData
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/models/__init__.py", line 6, in <module>
    from .parser import (get_pbparser,
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/models/parser.py", line 12, in <module>
    import jsonschema
ImportError: No module named jsonschema
```

I can then install jsonschem various ways (pip, conda install, or re-do conda create with "genomicconsensus jsonschema". All lead to the following error:
```
Traceback (most recent call last):
  File "/users/jurban/data/software/conda/anaconda3/envs/quiver/bin/variantCaller", line 3, in <module>
    from GenomicConsensus.main import main
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 42, in <module>
    from pbcore.io import AlignmentSet
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/__init__.py", line 38, in <module>
    from .align   import *
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/align/BamIO.py", line 35, in <module>
    from pysam import AlignmentFile
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /users/jurban/software/localpy/lib/python2.7/site-packages/pysam-0.9.1.4-py2.7-linux-x86_64.egg/pysam/libchtslib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```

I can then try several things such as force installing pysam, numpy, or scipy -- all seem to lead to this:
```
##example
conda install --force -n quiver -c bioconda genomicconsensus jsonschema pysam

quiver -h

Traceback (most recent call last):
  File "/users/jurban/data/software/conda/anaconda3/envs/quiver/bin/variantCaller", line 3, in <module>
    from GenomicConsensus.main import main
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 36, in <module>
    import argparse, atexit, cProfile, gc, glob, h5py, logging, multiprocessing
  File "/users/jurban/data/software/conda/anaconda3/envs/quiver/lib/python2.7/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/numpy.pxd", line 66, in init h5py.h5t
ImportError: No module named numpy
```

Then I tried various ways of installing numpy or force installing genomicconsensus -- but I just go through a loop between the last 2 errors.

Overall, I'd be happy to either debug the new issue on my older install or to successfully re-install it with conda. Any suggestions would be appreciated.

Many thanks,

John Urban

**Comment by JohnUrban** [comment]
So I may have found a solution for fixing my older version (quiver/GenomicConsensus 1.1.0) -- I know that it at least lets me get away with any of the following to see the help message:
```
quiver -h
#or 
python /path/to/variantCaller -h
```

Basically I needed to comment out lines for ```--verbose``` and ``--quiet``` in ```GenomicConsensus/options.py```:

```
## with line numbers
   308	#    debugging.add_argument(
   309	#        "--verbose",
   310	#        dest="verbosity",
   311	#        action="count",
   312	#        help="Set the verbosity level.")
   313	#    debugging.add_argument(
   314	#        "--quiet",
   315	#        dest="quiet",
   316	#        action="store_true",
   317	#        help="Turn off all logging, including warnings")

```

Note:
```
quiver --version
1.1.0
## also says this in GenomicConsensus/__init__.py
```


When I do ```quiver -h```, I get:
```
usage: variantCaller [-h] [--version] [--emit-tool-contract]
                     [--resolved-tool-contract RESOLVED_TOOL_CONTRACT]
                     [--log-file LOG_FILE]
                     [--log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL} | --debug | --quiet | -v]
                     --referenceFilename REFERENCEFILENAME -o OUTPUTFILENAMES
                     [-j NUMWORKERS] [--minConfidence MINCONFIDENCE]
                     [--minCoverage MINCOVERAGE]
                     [--noEvidenceConsensusCall {nocall,reference,lowercasereference}]
                     [--coverage COVERAGE] [--minMapQV MINMAPQV]
                     [--referenceWindow REFERENCEWINDOWSASSTRING]
                     [--alignmentSetRefWindows]
                     [--referenceWindowsFile REFERENCEWINDOWSASSTRING]
                     [--barcode _BARCODE] [--readStratum READSTRATUM]
                     [--algorithm ALGORITHM] [--parametersFile PARAMETERSFILE]
                     [--parametersSpec PARAMETERSSPEC] [--profile]
                     [--dumpEvidence [{variants,all}]]
                     [--evidenceDirectory EVIDENCEDIRECTORY] [--annotateGFF]
                     [--diploid] [--queueSize QUEUESIZE] [--threaded]
                     [--referenceChunkSize REFERENCECHUNKSIZE]
                     [--fancyChunking] [--simpleChunking]
                     [--referenceChunkOverlap REFERENCECHUNKOVERLAP]
                     [--autoDisableHdf5ChunkCache AUTODISABLEHDF5CHUNKCACHE]
                     [--aligner {affine,simple}] [--refineDinucleotideRepeats]
                     [--noRefineDinucleotideRepeats] [--fast]
                     [--skipUnrecognizedContigs]
                     inputFilename

Compute genomic consensus and call variants relative to the reference.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --emit-tool-contract  Emit Tool Contract to stdout (default: False)
  --resolved-tool-contract RESOLVED_TOOL_CONTRACT
                        Run Tool directly from a PacBio Resolved tool contract
                        (default: None)
  --log-file LOG_FILE   Write the log to file. Default(None) will write to
                        stdout. (default: None)
  --log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}
                        Set log level (default: INFO)
  --debug               Alias for setting log level to DEBUG (default: False)
  --quiet               Alias for setting log level to CRITICAL to suppress
                        output. (default: False)
  -v, --verbose         Set the verbosity level. (default: None)

Basic required options:
  inputFilename         The input cmp.h5 file
  --referenceFilename REFERENCEFILENAME, --reference REFERENCEFILENAME, -r REFERENCEFILENAME
                        The filename of the reference FASTA file (default:
                        None)
  -o OUTPUTFILENAMES, --outputFilename OUTPUTFILENAMES
                        The output filename(s), as a comma-separated
                        list.Valid output formats are .fa/.fasta, .fq/.fastq,
                        .gff (default: [])

Parallelism:
  -j NUMWORKERS, --numWorkers NUMWORKERS
                        The number of worker processes to be used (default: 1)

Output filtering:
  --minConfidence MINCONFIDENCE, -q MINCONFIDENCE
                        The minimum confidence for a variant call to be output
                        to variants.gff (default: 40)
  --minCoverage MINCOVERAGE, -x MINCOVERAGE
                        The minimum site coverage that must be achieved for
                        variant calls and consensus to be calculated for a
                        site. (default: 5)
  --noEvidenceConsensusCall {nocall,reference,lowercasereference}
                        The consensus base that will be output for sites with
                        no effective coverage. (default: lowercasereference)

Read selection/filtering:
  --coverage COVERAGE, -X COVERAGE
                        A designation of the maximum coverage level to be used
                        for analysis. Exact interpretation is algorithm-
                        specific. (default: 100)
  --minMapQV MINMAPQV, -m MINMAPQV
                        The minimum MapQV for reads that will be used for
                        analysis. (default: 10)
  --referenceWindow REFERENCEWINDOWSASSTRING, --referenceWindows REFERENCEWINDOWSASSTRING, -w REFERENCEWINDOWSASSTRING
                        The window (or multiple comma-delimited windows) of
                        the reference to be processed, in the format refGroup
                        :refStart-refEnd (default: entire reference).
                        (default: None)
  --alignmentSetRefWindows
                        The window (or multiple comma-delimited windows) of
                        the reference to be processed, in the format refGroup
                        :refStart-refEnd will be pulled from the alignment
                        file. (default: False)
  --referenceWindowsFile REFERENCEWINDOWSASSTRING, -W REFERENCEWINDOWSASSTRING
                        A file containing reference window designations, one
                        per line (default: None)
  --barcode _BARCODE    Only process reads with the given barcode name.
                        (default: None)
  --readStratum READSTRATUM
                        A string of the form 'n/N', where n, and N are
                        integers, 0 <= n < N, designating that the reads are
                        to be deterministically split into N strata of roughly
                        even size, and stratum n is to be used for variant and
                        consensus calling. This is mostly useful for Quiver
                        development. (default: None)

Algorithm and parameter settings:
  --algorithm ALGORITHM
  --parametersFile PARAMETERSFILE, -P PARAMETERSFILE
                        Parameter set filename (QuiverParameters.ini), or
                        directory D such that either
                        D/*/GenomicConsensus/QuiverParameters.ini, or
                        D/GenomicConsensus/QuiverParameters.ini, is found. In
                        the former case, the lexically largest path is chosen.
                        (default: None)
  --parametersSpec PARAMETERSSPEC, -p PARAMETERSSPEC
                        Name of parameter set (chemistry.model) to select from
                        the parameters file, or just the name of the
                        chemistry, in which case the best available model is
                        chosen. Default is 'auto', which selects the best
                        parameter set from the cmp.h5 (default: auto)

Verbosity and debugging/profiling:
  --profile             Enable Python-level profiling (using cProfile).
                        (default: False)
  --dumpEvidence [{variants,all}], -d [{variants,all}]
  --evidenceDirectory EVIDENCEDIRECTORY
  --annotateGFF         Augment GFF variant records with additional
                        information (default: False)

Advanced configuration options:
  --diploid             Enable detection of heterozygous variants
                        (experimental) (default: False)
  --queueSize QUEUESIZE, -Q QUEUESIZE
  --threaded, -T        Run threads instead of processes (for debugging
                        purposes only) (default: False)
  --referenceChunkSize REFERENCECHUNKSIZE, -C REFERENCECHUNKSIZE
  --fancyChunking       Adaptive reference chunking designed to handle
                        coverage cutouts better (default: True)
  --simpleChunking      Disable adaptive reference chunking (default: True)
  --referenceChunkOverlap REFERENCECHUNKOVERLAP
  --autoDisableHdf5ChunkCache AUTODISABLEHDF5CHUNKCACHE
                        Disable the HDF5 chunk cache when the number of
                        datasets in the cmp.h5 exceeds the given threshold
                        (default: 500)
  --aligner {affine,simple}, -a {affine,simple}
                        The pairwise alignment algorithm that will be used to
                        produce variant calls from the consensus (Quiver
                        only). (default: affine)
  --refineDinucleotideRepeats
                        Require quiver maximum likelihood search to try one
                        less/more repeat copy in dinucleotide repeats, which
                        seem to be the most frequent cause of suboptimal
                        convergence (getting trapped in local optimum) (Quiver
                        only) (default: True)
  --noRefineDinucleotideRepeats
                        Disable dinucleotide refinement (default: True)
  --fast                Cut some corners to run faster. Unsupported! (default:
                        False)
  --skipUnrecognizedContigs
                        Do not abort when told to process a reference window
                        (via -w/--referenceWindow[s]) that has no aligned
                        coverage. Outputs emptyish files if there are no
                        remaining non-degenerate windows. Only intended for
                        use by smrtpipe scatter/gather. (default: False)
```

I noticed that ```--verbosity/--quiet``` were both in the optional arguments -- and were in "Verbosity and debugging/profiling" before I commented them out. 

Was this a problem with the ```logging``` module perhaps?

I will let you know if I actually get it to run/repeat my work from a few years ago. Thanks for any comments you may still have to give.

Best,

John

p.s. I still have no solution for successfully installing genomicconsensus through conda.

**Comment by JohnUrban** [comment]
Well it ran a little bit -- but got this error:
```
[INFO] h5py version: 2.5.0
[INFO] hdf5 version: 1.8.14
[INFO] ConsensusCore version: 1.0.1
[INFO] Starting.
[INFO] Chemistry information could not be found in cmp.h5, cannot fix the readGroupTable or MovieID field.
[INFO] Peeking at file /gpfs/scratch/jurban/asm/eval/quiver/out_all.cmp.h5
[INFO] Input data: numAlnHits=1846463
[INFO] Loading reference
[INFO] Loaded 607 of 607 reference groups from /gpfs/scratch/jurban/asm/eval/asm.fa 
[INFO] Using Quiver parameters file /gpfs_home/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/quiver/resources/2014-09/GenomicConsensus/QuiverParameters.ini
[ERROR] Chemistry information could not be found in cmp.h5!
Traceback (most recent call last):
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 367, in args_runner
    return tr.main()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 291, in main
    self._configureAlgorithm(options, peekFile)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/main.py", line 192, in _configureAlgorithm
    self._algorithmConfiguration = self._algorithm.configure(options, cmpH5)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 252, in configure
    params = M.loadParameterSets(options.parametersFile, cmpH5=cmpH5)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/GenomicConsensus/quiver/model.py", line 412, in loadParameterSets
    chemistryNames = list(set(cmpH5.sequencingChemistry))  # uniquify
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1801, in sequencingChemistry
    responses = self._pollResources(lambda x: x.sequencingChemistry)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1769, in _pollResources
    return [func(resource) for resource in self.resourceReaders()]
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1801, in <lambda>
    responses = self._pollResources(lambda x: x.sequencingChemistry)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcore-1.2.10-py2.7.egg/pbcore/io/align/CmpH5IO.py", line 911, in sequencingChemistry
    raise ChemistryLookupError, "Chemistry information could not be found in cmp.h5!"
ChemistryLookupError: Chemistry information could not be found in cmp.h5!
[INFO] exiting with return code 2 in 44.78 sec.
```

Again -- Im not sure why it used to work, but now doesn't.

**Comment by pb-dseifert** [comment]
What does `quiver --version` say?

**Comment by JohnUrban** [comment]
My older version (from 2015) of quiver is 1.1.0 -- as is the one that installs w/ conda.

**Comment by JohnUrban** [comment]
Right -- but somehow the bioconda installation is giving me 1.1.0. I'd be happy if it would install the latest version.

**Comment by pb-dseifert** [comment]
`conda update --all`?

**Comment by pb-dseifert** [comment]
Maybe also try setting up a fresh conda installation

**Comment by JohnUrban** [comment]
Thanks for the suggestions -- I'm also trying re-installing genomicconsensus via conda after blanking out my PYTHONPATH variable. That is often involved in issues like this as well.

**Comment by JohnUrban** [comment]
Well this is the trick to get genomicconsensus to install the way it was intended to be installed -- at least on my system:
```
export PYTHONPATH=""
conda create --force -n genomicconsensus -c bioconda genomicconsensus
```

Version:
```
quiver --version
2.3.2
```

No complaints give and no additional steps were needed at all.

**Comment by pb-dseifert** [comment]
Then we're done here I guess

**Comment by JohnUrban** [comment]
Follow-up:

I needed to install jsonschema as well to get quiver to work w/ the bioconda installation.

All the commands I needed to do are:
```
export PYTHONPATH=""
conda create --force -n genomicconsensus -c bioconda genomicconsensus
conda activate genomicconsensus
conda install --force -n genomicconsensus -c bioconda jsonschema
```

Though it could probably be done more simply by:
```
export PYTHONPATH=""
conda create --force -n genomicconsensus -c bioconda genomicconsensus jsonschema
```
