### ISSUE TITLE
Name conflicts with io and io.py ?

### ISSUE THREAD

**Issue by gouthamatla** [PacificBiosciences/GenomicConsensus#14]
I am trying to run quiver and getting following error. Is it because of naming conflicts ? how to solve this ?
 ```python
$ quiver 
Traceback (most recent call last):
  File "/usr/local/bin/variantCaller.py", line 4, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 22, in <module>
    import zipfile
  File "/usr/local/lib/python2.7/zipfile.py", line 6, in <module>
    import io
  File "/usr/local/lib/python2.7/site-packages/pbcore-0.8.5-py2.7.egg/pbcore/io/__init__.py", line 31, in <module>
    from .BasH5IO import *
  File "/usr/local/lib/python2.7/site-packages/pbcore-0.8.5-py2.7.egg/pbcore/io/BasH5IO.py", line 43, in <module>
    from pbcore.io.FofnIO import readFofn
  File "/usr/local/lib/python2.7/site-packages/pbcore-0.9.3-py2.7.egg/pbcore/io/__init__.py", line 31, in <module>
    from .BasH5IO import *
  File "/usr/local/lib/python2.7/site-packages/pbcore-0.9.3-py2.7.egg/pbcore/io/BasH5IO.py", line 43, in <module>
    from pbcore.io.FofnIO import readFofn
  File "/usr/local/lib/python2.7/site-packages/pbcore-0.9.3-py2.7.egg/pbcore/io/FofnIO.py", line 33, in <module>
    from pbcore.io.base import getFileHandle
  File "/usr/local/lib/python2.7/site-packages/pbcore-0.9.3-py2.7.egg/pbcore/io/base.py", line 35, in <module>
    import gzip
  File "/usr/local/lib/python2.7/gzip.py", line 36, in <module>
    class GzipFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'
```

**Comment by dalexander** [comment]
If you look at It looks like you have two versions of pbcore installed.  You had best use a clean virtualenv and try again.
