### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by guleiathms** [PacificBiosciences/GenomicConsensus#18]
What's the possible reason for the following error? Thanks.

(smrtanalysis-2.3.0) lg140@clarinet002-063:/cmp$ variantCaller.py --verbose tmp.cmp.h5 --noEvidenceConsensusCall reference --minMapQV 30 --diploid --fancyChunking --aligner affine --refineDinucleotideRepeats -r /ref.fa -j 1 -o var_chr25.gff -o consensus_chr25.fa
[INFO] h5py version: 2.2.0
[INFO] hdf5 version: 1.8.12
[INFO] ConsensusCore version: 0.8.8
[INFO] Starting.
Traceback (most recent call last):
  File "/home/lg140/Programs/Tools/SMRT/current/analysis/bin/variantCaller.py", line 5, in <module>
    sys.exit(main())
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 367, in main
    return tr.main()
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 291, in main
    with CmpH5Reader(options.inputFilename) as peekCmpH5:
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/CmpH5IO.py", line 859, in __init__
    self._readLocatorById[refId] = makeReadLocator(self, refId)
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/rangeQueries.py", line 132, in makeReadLocator
    offStart, offEnd = offsets[offsets[:,0] == refSeq, 1:3].ravel()
ValueError: need more than 0 values to unpack

**Comment by dalexander** [comment]
Are you using the latest patch release?

**Comment by guleiathms** [comment]
Here is the version info. It works for some cmp.h5 files. So I guess the problem is from the cmp.h5 file.

(smrtanalysis-2.3.0) lg140@clarinet002-064:~$ variantCaller.py --version
  GenomicConsensus version: 0.9.2
  ConsensusCore version: 0.8.8
  h5py version: 2.2.0
  hdf5 version: 1.8.12

**Comment by dalexander** [comment]
I think your file is malformed

/cc @PacificBiosciences/techsupport

**Comment by guleiathms** [comment]
Maybe, I am checking whether there is anything wrong from the previous step.
Should I also upload the cmp.h5 file to your ftp?
Thanks.
/cc @PacificBiosciences/techsupport

**Comment by guleiathms** [comment]
Hi Dave,

Just want to update the error info, I found there is some error occurred during the mapping stage. The raw data is downloaded from SRA. It's from the Chemistry 1 system, so only has bas.h5 files.

When I use "pbalign --verbose --nproc 8 --forQuiver --byread --metrics DeletionQV,IPD,InsertionQV,PulseWidth,QualityValue,MergeQV,SubstitutionQV,DeletionTag --tmpDir ${temp} ${data} ${ref} ${output}ID.cmp.h5"

I got the following error:

2015-06-30 16:27:12,642 [INFO] pbalign version: 0.2.0.138342
2015-06-30 16:27:14,927 [INFO] BlasrService: Align reads to references using blasr.
2015-06-30 17:22:40,859 [INFO] FilterService: Filter alignments using samFilter.
2015-06-30 17:23:40,657 [INFO] OutputService: Genearte the output CMP.H5 file using samtoh5.
2015-06-30 17:25:16,934 [INFO] ForQuiverService: Sort.
2015-06-30 17:25:17,113 [INFO] SortService: Sort a cmp.h5 file using cmph5tools.py.
2015-06-30 17:25:20,955 [INFO] ForQuiverService: LoadPulses.
2015-06-30 17:25:21,129 [INFO] LoadPulsesService: Load pulses using loadPulses.
2015-06-30 17:29:04,267 [INFO] ForQuiverService: LoadChemistry.
2015-06-30 17:29:04,436 [INFO] LoadChemistryService: Load pulses using loadChemistry.py.
2015-06-30 17:29:06,841 [ERROR] LoadChemistryService returned a non-zero exit status. Traceback (most recent call last):
  File "/home/lg140/Programs/Tools/SMRT/current/analysis/bin/loadChemistry.py", line 8, in <module>
    load_entry_point('pbalign==0.2.0', 'console_scripts', 'loadChemistry.py')()
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbalign/tools/loadChemistry.py", line 72, in main
    chemTriple = bas.chemistryBarcodeTriple
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 860, in chemistryBarcodeTriple
    return self._parts[0].chemistryBarcodeTriple
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 624, in chemistryBarcodeTriple
    raise ChemistryLookupError, "Could not find chemistry barcodes in file or companion metadata.xml"
pbcore.chemistry.chemistry.ChemistryLookupError: Could not find chemistry barcodes in file or companion metadata.xml

 But, I still got the cmp.h5 files and they can be further merged, sorted and repacked. Then the initial problem comes in the Quiver stage. So how to solve this problem?
Thanks.

**Comment by dalexander** [comment]
Older bax files did not have the chemistry information so a `metadata.xml` file was required.  

If you know the exact chemistry that was used, you can specify it on your command line, i.e.

``
quiver -p P4-C2 myfile.cmp.h5 ....
```

(if the chemistry was P4-C2)

**Comment by guleiathms** [comment]
Thanks Dave,
I guess it's from RS I system, because it says Chemistry 1 (http://www.ncbi.nlm.nih.gov/sra/SRX638310)
What should I write here P?-C1?

**Comment by dalexander** [comment]
Need some help here tech support!  Some data got on SRA and there's no metadata.xml files or any mention of the chemistry used.

/cc @PacificBiosciences/techsupport

**Comment by dalexander** [comment]
Is this resolved?

**Comment by guleiathms** [comment]
yep, solved.


2015-08-20 10:51 GMT-04:00 David Alexander <notifications@github.com>:
