### ISSUE TITLE
some new error when using Quiver

### ISSUE THREAD

**Issue by guleiathms** [PacificBiosciences/GenomicConsensus#19]
I got some new error when using Quiver. What does this error mean?
...
[INFO] Quiver operating on chr6:86061995-86062505
[INFO] Quiver operating on chr6:86062495-86063005
[INFO] Quiver operating on chr6:86062995-86063505
[INFO] Quiver operating on chr6:86063495-86064005
[INFO] Quiver operating on chr6:86063995-86064505
[INFO] Quiver operating on chr6:86064495-86065005
[INFO] Quiver operating on chr6:86064995-86065505
[INFO] Quiver operating on chr6:86065495-86066005
[INFO] Quiver operating on chr6:86065995-86066505
Process QuiverWorkerProcess-10:
Traceback (most recent call last):
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 91, in run
    self._run()
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 196, in onChunk
    refContig, options.coverage, self.quiverConfig)
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 116, in consensusAndVariantsForWindow
    quiverConfig)
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/utils.py", line 383, in consensusForAlignments
    refineDinucleotideRepeats(mms)
  File "/home/lg140/Programs/Tools/SMRT/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/utils.py", line 164, in refineDinucleotideRepeats
    return cc.RefineDinucleotideRepeats(mms)
RuntimeError: Invalid input!
[INFO] Quiver operating on chr6:86066495-86067005
[ERROR] Child process exited with exitcode=1.  Aborting.
[INFO] Quiver operating on chr6:86066995-86067505
[ERROR] Aborting

**Comment by dalexander** [comment]
What is the output of ``quiver --version``?

**Comment by guleiathms** [comment]
(smrtanalysis-2.3.0) lg140@clarinet002-061:~$ quiver --version
  GenomicConsensus version: 0.9.2
  ConsensusCore version: 0.8.8
  h5py version: 2.2.0
  hdf5 version: 1.8.12

**Comment by dalexander** [comment]
In order to debug this issue I suspect we will need to get access to your files---either you can upload them to our FTP, or we could ssh to your cluster.  I suppose it depends on how big these files are.

**Comment by guleiathms** [comment]
It's just 16GB, I can upload it to your ftp, could you please ask Joseph to let me access your ftp again?
Thanks.

**Comment by dalexander** [comment]
Joey can you please give FTP access?

/cc @PacificBiosciences/techsupport

**Comment by dalexander** [comment]
please give the reference and the cmp.h5

**Comment by guleiathms** [comment]
Thanks, I will upload both.

**Comment by guleiathms** [comment]
Dave, I didn't get any info from Joey yet, not sure Joey saw your message.

**Comment by jkaralius** [comment]
Lei,

I sent you an email confirming the FTP credentials.

Joey

**Comment by guleiathms** [comment]
Uploaded all files, please take a look.
Thanks.
Lei

**Comment by dalexander** [comment]
Thanks.  I can reproduce the problem.  Will comment shortly.

**Comment by dalexander** [comment]
Remove `--diploid` from your command and it will work fine.  The "diploid" mode  is not reliable, I don't recommend using it at this time.

**Comment by guleiathms** [comment]
Thanks Dave.
