### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/GenomicConsensus#21]
Hi Quiver developers,

I aligned pacbio reads with blasr(bundled with smrtanalysis_2.3.0.140936) and tried to use quiver to call consensus. I got the following error, what is the problem here? Thanks!
```
$ quiver --version
  GenomicConsensus version: 1.1.0
  ConsensusCore version: 1.0.1
  h5py version: 2.5.0
  hdf5 version: 1.8.15
```
```
$ quiver ./try.cmp.h5 -r GCA_000001405.15_GRCh38_no_alt_analysis_set.fa -o variants.gff -o consensus.fasta
Process QuiverWorkerProcess-1:
Traceback (most recent call last):
  File "/home/yunfeiguo/Downloads/python_install/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/yunfeiguo/Downloads/python_install/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/Worker.py", line 96, in run
    self._run()
  File "/home/yunfeiguo/Downloads/python_install/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/home/yunfeiguo/Downloads/python_install/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/quiver/quiver.py", line 196, in onChunk
    refContig, options.coverage, self.quiverConfig)
  File "/home/yunfeiguo/Downloads/python_install/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/quiver/quiver.py", line 118, in consensusAndVariantsForWindow
    siteCoverage = U.coverageInWindow(subWin, alns)
  File "/home/yunfeiguo/Downloads/python_install/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/quiver/utils.py", line 404, in coverageInWindow
    tStart = a[:,0]
IndexError: too many indices for array
[ERROR] Child process exited with exitcode=1.  Aborting.

```

**Comment by dalexander** [comment]
can you share a small cmp.h5 file and reference? (you can send by private email)  If so, I can take a look.

**Comment by yunfeiguo** [comment]
Thanks! I managed to run it with smryportal bundled quiver.

On Aug 18, 2015, at 2:23 PM, David Alexander <notifications@github.com> wrote:

can you share a small cmp.h5 file and reference? (you can send by private email) If so, I can take a look.
