### ISSUE TITLE
AttributeError: can't set attribute (DataSetIO.py)

### ISSUE THREAD

**Issue by ifiddes** [PacificBiosciences/GenomicConsensus#24]
I am trying to run quiver on a group of BAMs produced by blasr (after downloading PacBio fastqs from SRA), and am getting the following error:

    (py2.7.9)kolossus Tue Sep 08 11:40 bin $./quiver -j30 chm1_test.fofn -r ~/ifiddes_hive/chr1_fastas/hg38_chr1.fa -o variants.gff -o consensus.fasta
    [WARNING] 'fancyChunking' not yet available for BAM files without accompanying .pbi files, disabling
    [ERROR] can't set attribute
    Traceback (most recent call last):
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/pbcommand-0.2.8-py2.7.egg/pbcommand/cli/core.py", line 76, in _pacbio_main_runner
        return_code = func(*args, **kwargs)
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/main.py", line 367, in args_runner
        return tr.main()
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/main.py", line 287, in main
        logging.info("Input data: numAlnHits=%d" % len(peekFile))
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/pbcore-1.2.2-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2310, in __len__
        self.numRecords = count
    AttributeError: can't set attribute
    Traceback (most recent call last):
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/pbcommand-0.2.8-py2.7.egg/pbcommand/cli/core.py", line 76, in _pacbio_main_runner
        return_code = func(*args, **kwargs)
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/main.py", line 367, in args_runner
        return tr.main()
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/main.py", line 287, in main
        logging.info("Input data: numAlnHits=%d" % len(peekFile))
      File "/cluster/home/ifiddes/virtualenvs/py2.7.9/lib/python2.7/site-packages/pbcore-1.2.2-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2310, in __len__
        self.numRecords = count
    AttributeError: can't set attribute

**Comment by dalexander** [comment]
@mdsmith, any idea?

**Comment by mdsmith** [comment]
That fancyChunking warning and the lack of a numRecords setter suggests that out of date GenomicConsensus and pbcore may have slipped into use. This could be a tagged release compatibility issue, but with current tagged releases and mainlines we shouldn't see either of those. (See also the pbcore-1.2.2 version number in the error message).

**Comment by dalexander** [comment]
OK.  OP: Try again with more recent code.
