### ISSUE TITLE
ConsensusCaller - 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/GenomicConsensus#26]
Dear Quiver developers,

I got the following errors running quiver (PBSuite_15.2.20). The `*.spots` file only contains a few lines of output. The tail calling step finished without error. Could you suggest where went wrong? Thanks!

The command was
```
Honey.py spots $BAM --reference $REF
```
```
2015-09-14 13:46:18,726 [INFO] Starting chrUn_KI270581v1:SpotCaller
2015-09-14 13:46:18,728 [INFO] |chrUn_KI270581v1:SpotCaller|COV processing
2015-09-14 13:46:18,728 [INFO] |chrUn_KI270581v1:SpotCaller|MaxCov:72 MeanCov:38 StdCov:20 MinCov:20
2015-09-14 13:46:18,728 [INFO] |chrUn_KI270581v1:SpotCaller|INS processing
2015-09-14 13:46:18,728 [INFO] |chrUn_KI270581v1:SpotCaller|RateMean 0.724099  -- RateStd  0.446967
2015-09-14 13:46:18,758 [INFO] |chrUn_KI270581v1:SpotCaller|DEL processing
2015-09-14 13:46:18,759 [INFO] |chrUn_KI270581v1:SpotCaller|RateMean 0.341754  -- RateStd  0.474298
2015-09-14 13:46:18,762 [INFO] Starting chrUn_KI270748v1:68226-68288:ConsensusCaller
2015-09-14 13:46:18,795 [ERROR] Exception raised in task chrUn_KI270748v1:68226-68288:ConsensusCaller - 'NoneType' object has no attribute '__getitem__'
2015-09-14 13:46:18,795 [ERROR] Dumping Traceback:
2015-09-14 13:46:18,915 [INFO] Starting chrUn_KI270748v1:66663-66798:ConsensusCaller
2015-09-14 13:46:18,915 [ERROR] Task chrUn_KI270748v1:68226-68288:ConsensusCaller Failed ('NoneType' object has no attribute '__getitem__')
2015-09-14 13:46:18,927 [ERROR] Exception raised in task chrUn_KI270748v1:66663-66798:ConsensusCaller - 'NoneType' object has no attribute '__getitem__'
2015-09-14 13:46:18,927 [ERROR] Dumping Traceback:
2015-09-14 13:46:18,928 [INFO] Starting chrUn_KI270748v1:79872-81817:ConsensusCaller
2015-09-14 13:46:18,928 [ERROR] Task chrUn_KI270748v1:66663-66798:ConsensusCaller Failed ('NoneType' object has no attribute '__getitem__')
2015-09-14 13:46:18,947 [ERROR] Exception raised in task chrUn_KI270748v1:79872-81817:ConsensusCaller - 'NoneType' object has no attribute '__getitem__'
2015-09-14 13:46:18,947 [ERROR] Dumping Traceback:
2015-09-14 13:46:18,947 [INFO] Starting chrUn_KI270749v1:24494-25113:ConsensusCaller
2015-09-14 13:46:18,947 [ERROR] Task chrUn_KI270748v1:79872-81817:ConsensusCaller Failed ('NoneType' object has no attribute '__getitem__')
2015-09-14 13:46:18,973 [ERROR] Exception raised in task chrUn_KI270749v1:24494-25113:ConsensusCaller - 'NoneType' object has no attribute '__getitem__'
...
Traceback (most recent call last):
  File "/home/yunfeiguo/Downloads/PBSuite_15.2.20/pbsuite/honey/HSpots.py", line 498, in run
    next_task(self.bam, self.reference, self.honH5)
  File "/home/yunfeiguo/Downloads/PBSuite_15.2.20/pbsuite/honey/HSpots.py", line 1074, in __call__
    self.newSpots = self.consensusCalling(self.spot, bam, reference, self.args)
  File "/home/yunfeiguo/Downloads/PBSuite_15.2.20/pbsuite/honey/HSpots.py", line 908, in consensusCalling
    seq, qual = self.readTrim(read, start-buffer, end+buffer)
  File "/home/yunfeiguo/Downloads/PBSuite_15.2.20/pbsuite/honey/HSpots.py", line 882, in readTrim
    qual = read.qqual[trimS:trimE]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by dalexander** [comment]
this is third-party software, not pacbio's

**Comment by yunfeiguo** [comment]
Sorry, I should have posted it elsewhere.
