### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/GenomicConsensus#27]
Dear Quiver developers,

My instance of quiver aborted after a couple of days of running. Can you give some clue how to debug? Our machine has 1TB of memory and there is no limit for memory usage. Thanks!
command
```
source `/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/admin/bin/getsetupfile`
quiver -j 32 merge.cmp.h5 -r my.fa -o ps.fasta -o ps.gff
```
version
```
(smrtanalysis-2.3.0) [12:00 yunfeiguo@biocluster quiver]$ quiver --version
  GenomicConsensus version: 0.9.2
  ConsensusCore version: 0.8.8
  h5py version: 2.2.0
  hdf5 version: 1.8.12
```
error 
```
Traceback (most recent call last):
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/variantCaller.py", line 5, in <module>
    sys.exit(main())
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 367, in main
    return tr.main()
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 291, in main
    with CmpH5Reader(options.inputFilename) as peekCmpH5:
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbcore/io/CmpH5IO.py", line 780, in __init__
    self._alignmentGroupById[alnGroupId] = dict(alnGroup.items())
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/base.py", line 347, in items
    return [(x, self.get(x)) for x in self]
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 191, in get
    return self[name]
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/group.py", line 159, in __getitem__
    return dataset.Dataset(oid)
  File "/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 244, in __init__
    self._dcpl = self.id.get_create_plist()
  File "h5d.pyx", line 313, in h5py.h5d.DatasetID.get_create_plist (h5py/h5d.c:3508)
ValueError: not a dataset (Invalid arguments to routine: Inappropriate type)
/share/apps/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/quiver: line 2: 30343 Segmentation fault      variantCaller.py --algorithm=quiver $*
```

**Comment by yunfeiguo** [comment]
Any suggestions? Thanks!

**Comment by pb-jlandolin** [comment]
Hello yunfeiguo,

Please use the quiver version that is included in SMRT Analysis.  The install and deployment of tools is much more streamlined and you don't have to build anything from source.

http://www.pacb.com/support/software-downloads/


After installing, you can just do:

```
source /opt/smrtanalysis/current/etc/setup.sh
quiver aligned_reads{.cmp.h5, .bam, .fofn, or .xml}  -r reference{.fasta or .xml} -o variants.gff  -o consensus.fasta -o consensus.fastq
```

For more details on running smrtpipe and other command-line tools with your SMRT Analysis install:
http://www.pacb.com/wp-content/uploads/2015/09/SMRT-Pipe-Reference-Guide.pdf
