### ISSUE TITLE
Quiver error. Installation successfull but while runnning throwing error

### ISSUE THREAD

**Issue by sudhirjadhao** [PacificBiosciences/GenomicConsensus#29]
Quiver installed successfully but while running throwing below error
```python
$ quiver 

Traceback (most recent call last):
  File "/usr/local/bin/variantCaller", line 4, in <module>
    __import__('pkg_resources').run_script('GenomicConsensus==1.1.0', 'variantCaller')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
    
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
    
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/EGG-INFO/scripts/variantCaller", line 3, in <module>
    from GenomicConsensus.main import main
  File "/home/bionivid-server/.local/lib/python2.7/site-packages/GenomicConsensus-1.1.0-py2.7.egg/GenomicConsensus/main.py", line 42, in <module>
    from pbcore.io import AlignmentSet
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/__init__.py", line 38, in <module>
    from .align   import *
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 45, in <module>
    from .PacBioBamIndex import PacBioBamIndex
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/PacBioBamIndex.py", line 40, in <module>
    from ._BamSupport import IncompatibleFile
  File "/usr/local/lib/python2.7/dist-packages/pbcore/io/align/_BamSupport.py", line 58, in <module>
    complementAscii = np.vectorize(ASCII_COMPLEMENT_MAP.get, otypes=[np.int8])
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1818, in __init__
    nin, ndefault = _get_nargs(pyfunc)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 1750, in _get_nargs
    "failed to determine the number of arguments for %s" % (obj))
ValueError: failed to determine the number of arguments for <built-in method get of dict object at 0x3217680>
```
Can anyone please tell me where I am going wrong

**Comment by sudhirjadhao** [comment]
error solved. I think the problem was in python version and its path
