### ISSUE TITLE
AssertionError when using .fofn

### ISSUE THREAD

**Issue by SethM55** [PacificBiosciences/GenomicConsensus#36]
Hello,

In trying to run several cmp.hd5 files against the same reference I used the fofn option as described in the FAQ.  This led to every attempt generating the same set of error messages:

    [ERROR] 
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pbcommand-0.2.17-py2.7.egg/pbcommand/cli/core.py", line 76, in _pacbio_main_runner
    return_code = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 375, in args_runner
    return tr.main()
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 297, in main
    self._loadReference(peekFile)
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 159, in _loadReference
    err = reference.loadFromFile(options.referenceFilename, alnFile)
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/reference.py", line 133, in loadFromFile
    cmpContigNames = set(alnFile.refNames)
      File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.6-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2325, in refNames
    self.refInfo('FullName')]
      File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.6-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 3165, in refInfo
    names = self.referenceInfoTable['Name']
      File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.6-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 3079, in referenceInfoTable
    assert not self.isCmpH5 # see above
    AssertionError
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pbcommand-0.2.17-py2.7.egg/pbcommand/cli/core.py", line 76, in _pacbio_main_runner
    return_code = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 375, in args_runner
    return tr.main()
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 297, in main
    self._loadReference(peekFile)
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 159, in _loadReference
    err = reference.loadFromFile(options.referenceFilename, alnFile)
      File "/usr/local/lib/python2.7/dist-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/reference.py", line 133, in loadFromFile
    cmpContigNames = set(alnFile.refNames)
      File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.6-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2325, in refNames
    self.refInfo('FullName')]
      File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.6-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 3165, in refInfo
    names = self.referenceInfoTable['Name']
      File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.6-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 3079, in referenceInfoTable
    assert not self.isCmpH5 # see above
    AssertionError

I've tried making my fofn files look like this:

    PacBio_Run168-001-1.cmp.h5
    PacBio_Run168-001-2.cmp.h5
    PacBio_Run168-001-3.cmp.h5

or this:

    /genome/Data/FM_assembly/SARC1/PacBio_Run168-001-1.cmp.h5
    /genome/Data/FM_assembly/SARC1/PacBio_Run168-001-2.cmp.h5
    /genome/Data/FM_assembly/SARC1/PacBio_Run168-001-3.cmp.h5

And my quiver command is the following

    quiver -j 12 -r SARC1_Scaffolds.fasta -o SARC1_Run168-001_quiver_variants.gff -o quiver_Corrected_SARC1_Run168-001.fasta -o quiver_Corrected_SARC1_Run168-001.fastq SARC1_Run168-001.fofn

I can run each file individually, and it completes without error, but can't combine them into an fofn.

**Comment by dalexander** [comment]
@mdsmith , can you chime in here?

**Comment by mdsmith** [comment]
Hmmm, this is an unloved corner of the DataSet API. Cmp.h5 files contain metadata tables that don't merge particularly well. These assertions are a safeguard against the exposure of misinformation, but perhaps support for merged cmp.h5 files can be improved. I will see what I can do.

**Comment by mdsmith** [comment]
@SethM55, this should be working now with the tip of the master branch of pbcore and whatever Genomic Consensus you were using. Let me know if you continue to have issues.
