### ISSUE TITLE
KeyError: 'DS'

### ISSUE THREAD

**Issue by eltonjrv** [PacificBiosciences/GenomicConsensus#41]
Hello Quiver folks,

I am performing a separate PacBio assembly test with a new assembler called Miniasm (https://github.com/lh3/miniasm). Since it has no error correction step, I need to generate a consensus with quiver on a downstream analysis in order to get more accurate contigs.
I am getting the following error running quiver independently within the smartanalysis virtualenv:
#################
(smrtanalysis-2.3.0) elton@fera:/work/schisto/elton/PacBio/miniasm/quiver-run$ nice quiver -j8 all-h5-merged.sorted.bam -r pacbio-corrected-hybrid-miniasm.fasta -o variants.gff -o pacbio-corrected-hybrid-miniasm-quiverCons.fasta 

[WARNING] 'fancyChunking' not yet available for BAM, disabling
Traceback (most recent call last):
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/variantCaller.py", line 5, in <module>
    sys.exit(main())
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 367, in main
    return tr.main()
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/main.py", line 278, in main
    with BamReader(options.inputFilename) as peekCmpH5:
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/io/BamIO.py", line 100, in __init__
    self._loadReadGroupInfo()
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/io/BamIO.py", line 58, in _loadReadGroupInfo
    ds = dict([pair.split("=") for pair in rg["DS"].split(";") if pair != ""])
KeyError: 'DS' 
#################

Could anyone shed some light on this issue?
Thanks in advance,
Elton
Note: I generated my h5*.sam files with blasr. In addition, I have used samtools in order to get .bam, sorted.bam and all-merged.sorted.bam files.

**Comment by dalexander** [comment]
This BAM file is not (PacBio) spec-compliant, please see http://pacbiofileformats.readthedocs.org/en/3.0/
