### ISSUE TITLE
quiver terminates when running on large cmp.h5 file

### ISSUE THREAD

**Issue by MichelMoser** [PacificBiosciences/GenomicConsensus#45]
Hi i would like to report two issues when running quiver: 

Strange enough the errors occur only when reaching a certain number of SMRTcells ( > 10 ) used for polishing. 

First error when running quiver in default options: 

```
source /home/mmoser/PacBioScripts/pacbio_env/bin/activate

cmph5tools.py -v merge --outFile 10smrtcells.cmp.h5 1.pbout.cmp.h5 2.pbout.cmp.h5 3.pbout.cmp.h5 4.pbout.cmp.h5 5.pbout.cmp.h5 6.pbout.cmp.h5 7.pbout.cmp.h5 8.pbout.cmp.h5 9.pbout.cmp.h5 10.pbout.cmp.h5

cmph5tools.py sort  10smrtcells.cmp.h5 --deep --tmpDir /data1/projects/p023/quiver/tmp --outFile 10smrtcells.sorted.cmp.h5 

quiver --verbose -j8 10smrtcells.sorted.cmp.h5 -r PExserta.fasta -o quiv10smrt.test.consesus.fasta -o quiv10smrt.test.consensus.fastq

```

Exits with error: 

```
[INFO] Quiver operating on ctg7180000026299:75495-76005
[INFO] Quiver operating on ctg7180000026299:75995-76505
[INFO] Quiver operating on ctg7180000026299:76495-77005
Process QuiverWorkerProcess-2:
Traceback (most recent call last):
  File "/software/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 96, in run
    self._run()
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 197, in onChunk
    refContig, options.coverage, self.quiverConfig)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 104, in consensusAndVariantsForWindow
    clippedAlns_ = [ aln.clippedTo(*interval) for aln in alns ]
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/CmpH5IO.py", line 286, in clippedTo
    return ClippedCmpH5Alignment(self, refStart, refEnd)
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/CmpH5IO.py", line 639, in __init__
    refPositions = aln.referencePositions(orientation="genomic")
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/CmpH5IO.py", line 528, in referencePositions
    referenceNonGapMask = (self.alignmentArray(orientation) & 0b1111) != GAP
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/CmpH5IO.py", line 453, in alignmentArray
    alnArray = arrayFromDataset(alnDs, self.Offset_begin, self.Offset_end)
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/_utils.py", line 45, in arrayFromDataset
    ds.id.read(mspace, fspace, a)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/builddir/build/BUILD/h5py-2.5.0/h5py/_objects.c:2400)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/builddir/build/BUILD/h5py-2.5.0/h5py/_objects.c:2357)
  File "h5py/h5d.pyx", line 167, in h5py.h5d.DatasetID.read (/builddir/build/BUILD/h5py-2.5.0/h5py/h5d.c:2912)
  File "h5py/h5t.pyx", line 1468, in h5py.h5t.py_create (/builddir/build/BUILD/h5py-2.5.0/h5py/h5t.c:15336)
  File "h5py/h5t.pyx", line 1482, in h5py.h5t.py_create (/builddir/build/BUILD/h5py-2.5.0/h5py/h5t.c:14861)
  File "h5py/h5t.pyx", line 1302, in h5py.h5t._c_int (/builddir/build/BUILD/h5py-2.5.0/h5py/h5t.c:12735)
RuntimeError: Unable to register datatype atom (Can't insert duplicate key)
[INFO] Quiver operating on ctg7180000026299:76995-77505
[INFO] Quiver operating on ctg7180000026299:77495-78005
[INFO] Quiver operating on ctg7180000026299:77995-78505
[INFO] Quiver operating on ctg7180000026299:78495-79005
[INFO] Quiver operating on ctg7180000026299:78995-79505
[INFO] Quiver operating on ctg7180000026299:79495-80005
[INFO] Quiver operating on ctg7180000026299:79995-80505
[ERROR] Child process exited with exitcode=1.  Aborting.
[INFO] Quiver operating on ctg7180000026299:80495-81005
[ERROR] Aborting
[INFO] exiting with return code -1 in 54569.88 sec.
```
 

second error occurs when running quiver with the --referenceWindowFile option:
```
quiver --verbose -j16 --referenceWindowsFile test.rgn 10smrtcells.sorted.cmp.h5 -r PExserta.fasta -o quiv10smrt.test.rgn.consesus.fasta -o quiv10smrt.test.rgn.consensus.fastq

cat test.rgn: 

ctg7180000024811:1-28396
ctg7180000024812:1-10404
ctg7180000024813:1-61108
...

```
 Exits with error: 
```
[INFO] h5py version: 2.5.0
[INFO] hdf5 version: 1.8.13
[INFO] ConsensusCore version: 1.0.1
[INFO] ConsensusCore2 version: ConsensusCore2 unavailable
[INFO] Starting.
[INFO] Peeking at file /data1/projects/p023/P.EXSERTA/quiver/test/pex2_10smrtcells.sorted.cmp.h5
[INFO] Input data: numAlnHits=1240406
[INFO] Loading reference
[INFO] Loaded 20159 of 20159 reference groups from /data1/projects/p023/P.EXSERTA/quickmerge/pex2/PExserta/sequence/PExserta.fasta 
[ERROR] Unknown reference name: ctg7180000024833
Traceback (most recent call last):
  File "/software/UHTS/PacBio/pbcommand/0.3.9/lib/python2.7/site-packages/pbcommand/cli/core.py", line 104, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/main.py", line 375, in args_runner
    return tr.main()
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    self._loadReference(peekFile)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/main.py", line 176, in _loadReference
    options.referenceWindowsAsString.split(","))
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/reference.py", line 171, in stringToWindow
    refId    = anyKeyToId(m.group(1))
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/reference.py", line 95, in anyKeyToId
    raise Exception, "Unknown reference name: %s" % stringKey
Exception: Unknown reference name: ctg7180000024833
Traceback (most recent call last):
  File "/software/UHTS/PacBio/pbcommand/0.3.9/lib/python2.7/site-packages/pbcommand/cli/core.py", line 104, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/main.py", line 375, in args_runner
    return tr.main()
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/main.py", line 297, in main
    self._loadReference(peekFile)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/main.py", line 176, in _loadReference
    options.referenceWindowsAsString.split(","))
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/reference.py", line 171, in stringToWindow
    refId    = anyKeyToId(m.group(1))
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/reference.py", line 95, in anyKeyToId
    raise Exception, "Unknown reference name: %s" % stringKey
Exception: Unknown reference name: ctg7180000024833
[INFO] exiting with return code 2 in 2154.15 sec.

```
when checking for the sequence, i find it in the reference and in the region-file. 
Might there be no variants in the named sequence, which causes the error?

For the first error, i am wondering if it might be an issue with the hdf5 library or some integer overflow as a run with 2 merged smrtcells ran successfully.

Thank you, 
Michel

**Comment by dalexander** [comment]
First error: I have never seen this error before.   Indeed HDF5 is a bit flaky and weird, we are moving away from HDF5 to BAM in SMRTanalysis (SA) 3.0.  In practice, we do not recommend that people attempt to run enormous quiver jobs on a single node---it should be scatter/gathered across cluster nodes.  I am trying to find a link for you on how to do that with smrtpipe.

Second error:  Can you show me the complete reference name?  Are there some FASTA header "comments"?  In SMRTanalysis 2.3, IIRC you had to use the *complete* header as an identifier---the "prefix" was not sufficient. We have revised this in the forthcoming SA 3.0.

**Comment by dalexander** [comment]
Michel, I have posted instructions for how to run large-scale resequencing jobs using SMRTpipe here:

https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowTo.rst#running-a-large-scale-resequencingpolishing-job-in-smrtanalysis-23

I hope this will help you resolve your issue

**Comment by dalexander** [comment]
Closing.
