### ISSUE TITLE
Invalid input to cc.RefineDinucleotideRepeats(mms)

### ISSUE THREAD

**Issue by Tierhon** [PacificBiosciences/GenomicConsensus#49]
Hi,
I get this error when running quiver:
Process QuiverWorkerProcess-3:
Traceback (most recent call last):
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 91, in run
    self._run()
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 196, in onChunk
    refContig, options.coverage, self.quiverConfig)
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 116, in consensusAndVariantsForWindow
    quiverConfig)
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/utils.py", line 383, in consensusForAlignments
  File "/cluster/software/VERSIONS/smrtanalysis-2.3.0/redist/python2.7/lib/python2.7/site-packages/GenomicConsensus/quiver/utils.py", line 164, in refineDinucleotideRepeats
    return cc.RefineDinucleotideRepeats(mms)
RuntimeError: Invalid input!

I'm pretty sure I've seen that before also, but I don't remember what I did then. Maybe gave up quiver. I run quiver with these options:
quiver align/fish_all.cmp.h5 -j 32 -r fish_sga2.fasta -o fish_variants.gff -o fish_quiver_cns.fasta -o fish_quiver_cns.fastq -v -v -v 1> quiver.out 2> quiver.err
So I can't just remove --diploid as I saw recommended to someone else here. quiver --version gives this:
quiver --version
  GenomicConsensus version: 0.9.2
  ConsensusCore version: 0.8.8
  h5py version: 2.2.0
  hdf5 version: 1.8.12
(smrtanalysis-2.3.0)

I have the output log with three -v, but the output is a bit mangled since 32 processes output there. It ran for 29 hours with 32 processes, so running it single process is quite time demanding.

Would using   --noRefineDinucleotideRepeats help?

Thank you, 
Ole

**Comment by dalexander** [comment]
Dear @Tierhon, please forgive my delayed response, I did not see this message.  

You can try using --noRefineDinucleotideRepeats, but there will be a slightly higher consensus error rate expected.

Can you please contact me at dalexander@pacb.com and we can discuss?  I would like to try to figure this out.

**Comment by dalexander** [comment]
This issue has been fixed here: 

https://github.com/PacificBiosciences/ConsensusCore/commit/4a5e8bbcbd47958297c6406104d98c7f78278527

The forthcoming SMRTanalysis 3.1 release will contain the fix.

**Comment by dalexander** [comment]
Actually, I'm not sure that the fix will be in SA3.1 or SA3.1.1, but it will be available soon.  I will advise.
