### ISSUE TITLE
"tag 'qs' not present"

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/GenomicConsensus#69]
Hi there,

I tried to run quiver with latest blasr but got the following error. Can anyone help? Thanks!

```
$blasr5.0 -nproc 12 -sam input.fofn 000000F_left.fa > blasr5_0aln.sam
$samtools view -bS blasr5_0aln.sam | samtools sort - blasr5_0aln
$quiver blasr5_0aln.bam -r 000000F_left.fa -o 000000F_left_consensus.fasta -o 000000F_left_consensus.fastq -o 000000F_left_variants.gff

[WARNING] pbi file missing for /home/yunfeiguo/projects/PacBio_reference_genome/quiver/blasr5.0_test_20160321/blasr5_0aln.bam, operating with reduced speed and functionality
"tag 'qs' not present"
Traceback (most recent call last):
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcommand-0.3.18-py2.7.egg/pbcommand/cli/core.py", line 150, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 364, in args_runner
    return tr.main()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 277, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2364, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1769, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 429, in __init__
    self.updateCounts()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2204, in updateCounts
    self.assertIndexed()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2024, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1716, in _assertIndexed
    self._openFiles()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1840, in _openFiles
    if not list(itertools.islice(resource, 1)):
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamIO.py", line 340, in __iter__
    yield BamAlignment(self, a)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamAlignment.py", line 115, in __init__
    qs, qe = self.qStart, self.qEnd
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamAlignment.py", line 142, in qStart
    return self.peer.opt("qs")
  File "pysam/calignedsegment.pyx", line 2179, in pysam.calignedsegment.AlignedSegment.opt (pysam/calignedsegment.c:24897)
  File "pysam/calignedsegment.pyx", line 1851, in pysam.calignedsegment.AlignedSegment.get_tag (pysam/calignedsegment.c:19751)
KeyError: "tag 'qs' not present"
[ERROR] "tag 'qs' not present"
Traceback (most recent call last):
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcommand-0.3.18-py2.7.egg/pbcommand/cli/core.py", line 150, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 364, in args_runner
    return tr.main()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 277, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2364, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1769, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 429, in __init__
    self.updateCounts()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2204, in updateCounts
    self.assertIndexed()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2024, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1716, in _assertIndexed
    self._openFiles()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1840, in _openFiles
    if not list(itertools.islice(resource, 1)):
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamIO.py", line 340, in __iter__
    yield BamAlignment(self, a)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamAlignment.py", line 115, in __init__
    qs, qe = self.qStart, self.qEnd
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamAlignment.py", line 142, in qStart
    return self.peer.opt("qs")
  File "pysam/calignedsegment.pyx", line 2179, in pysam.calignedsegment.AlignedSegment.opt (pysam/calignedsegment.c:24897)
  File "pysam/calignedsegment.pyx", line 1851, in pysam.calignedsegment.AlignedSegment.get_tag (pysam/calignedsegment.c:19751)
KeyError: "tag 'qs' not present"
Traceback (most recent call last):
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcommand-0.3.18-py2.7.egg/pbcommand/cli/core.py", line 150, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 364, in args_runner
    return tr.main()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/GenomicConsensus-2.0.0-py2.7.egg/GenomicConsensus/main.py", line 277, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2364, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1769, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 429, in __init__
    self.updateCounts()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2204, in updateCounts
    self.assertIndexed()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2024, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1716, in _assertIndexed
    self._openFiles()
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1840, in _openFiles
    if not list(itertools.islice(resource, 1)):
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamIO.py", line 340, in __iter__
    yield BamAlignment(self, a)
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamAlignment.py", line 115, in __init__
    qs, qe = self.qStart, self.qEnd
  File "/home/yunfeiguo/projects/PacBio_reference_genome/quiver/quiver_install_20160307/lib/python2.7/site-packages/pbcore-1.2.8-py2.7.egg/pbcore/io/align/BamAlignment.py", line 142, in qStart
    return self.peer.opt("qs")
  File "pysam/calignedsegment.pyx", line 2179, in pysam.calignedsegment.AlignedSegment.opt (pysam/calignedsegment.c:24897)
  File "pysam/calignedsegment.pyx", line 1851, in pysam.calignedsegment.AlignedSegment.get_tag (pysam/calignedsegment.c:19751)
KeyError: "tag 'qs' not present"
```

version information
```
$ quiver --version
2.0.0
$ blasr5.0 -version
blasr   5.0
```

**Comment by dalexander** [comment]
@ylipacbio can you comment?

**Comment by dalexander** [comment]
Please use pbalign, don't use blasr directly.

The SAM output from BLASR does not respect the PacBio BAM spec.  I will ask the BLASR people to remove that output mode.
