### ISSUE TITLE
IOError running quiver

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/GenomicConsensus#85]
Hello
I am running in a problem while trying to polish a large genome with Quiver.
As always, I mapped the reads with pbalign, then merged them and sorted the cmp.h5 files.
This generated a 1.2 TB large file. Then I executed quiver:

    quiver -j30 settings2MergedForQuiver.cmp.h5 -r primaryContigs.fasta -o primaryContigs._variants.gff -o primaryContigs.Quiver.fasta -o primaryContigs.Quiver.fastq --log-file primaryContigs.log --diploid

And first, let me say it - it is incredibly slow. I think it manages like 30Mbp/h. And this is on a dedicated server with SSD. Then after 1 d it fails with the following error:

<pre><code>
Process QuiverWorkerProcess-2:
Traceback (most recent call last):
  File "/software/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 96, in run
    self._run()
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/Worker.py", line 77, in _run
    result = self.onChunk(datum)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 197, in onChunk
    refContig, options.coverage, self.quiverConfig)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/quiver.py", line 117, in consensusAndVariantsForWindow
    quiverConfig)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/utils.py", line 368, in consensusForAlignments
    mappedReads = [ quiverConfig.extractMappedRead(aln, refStart) for aln in alns ]
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/model.py", line 354, in extractMappedRead
    return model.extractMappedRead(aln, windowStart)
  File "/software/UHTS/PacBio/GenomicConsensus/2.0.0/lib/python2.7/site-packages/GenomicConsensus/quiver/model.py", line 139, in extractMappedRead
    name = aln.readName
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/_AlignmentMixin.py", line 189, in readName
    if self.readType == "CCS":
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/CmpH5IO.py", line 499, in readType
    return self.cmpH5.readType
  File "/software/UHTS/PacBio/pbcore/1.2.7/lib/python2.7/site-packages/pbcore/io/align/CmpH5IO.py", line 1022, in readType
    return self.file.attrs["ReadType"]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/builddir/build/BUILD/h5py-2.5.0/h5py/_objects.c:2400)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/builddir/build/BUILD/h5py-2.5.0/h5py/_objects.c:2357)
  File "/software/lib64/python2.7/site-packages/h5py/_hl/attrs.py", line 73, in __getitem__
    attr.read(arr, mtype=htype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/builddir/build/BUILD/h5py-2.5.0/h5py/_objects.c:2400)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/builddir/build/BUILD/h5py-2.5.0/h5py/_objects.c:2357)
  File "h5py/h5a.pyx", line 355, in h5py.h5a.AttrID.read (/builddir/build/BUILD/h5py-2.5.0/h5py/h5a.c:4962)
  File "h5py/_proxy.pyx", line 58, in h5py._proxy.attr_rw (/builddir/build/BUILD/h5py-2.5.0/h5py/_proxy.c:992)
IOError: Unable to read attribute (Can't insert duplicate key)
[ERROR] Child process exited with exitcode=1.  Aborting.
[ERROR] Aborting
</code></pre>

Any idea how to overcome this?

**Comment by dalexander** [comment]
https://github.com/PacificBiosciences/GenomicConsensus/blob/master/doc/HowTo.rst#running-a-large-scale-resequencingpolishing-job-in-smrtanalysis-23

**Comment by ebioman** [comment]
I am sorry, but I dont see at all how this answers my problem. No support outside of smrtpipe or what do you want to tell me ?

**Comment by dalexander** [comment]
right, sorry.  I clarified the wording there to more specifically address your question.

**Comment by ebioman** [comment]
In case anybody is at one point in a similar situation:

For me it seems that it only happens with very large contigs and the type of error points to a bug
know for HDF.1.8.13. It is supposed to be fixed with the newer version (>=1.8.14).

Cheers

**Comment by dalexander** [comment]
That's good to know!  Sorry I couldn't be of more help.
