### ISSUE TITLE
Badly behaved unit test

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/GenomicConsensus#99]
test_tool_contract.TestVariantCaller gives some oddball error message about logging:

```
$ nosetests -v tests/unit/test_tool_contract.py       [master] 
test_run_e2e (test_tool_contract.TestGffToBed) ... ok
test_run_e2e (test_tool_contract.TestGffToVcf) ... ok
test_run_e2e (test_tool_contract.TestSummarizeConsensus) ... ok
test_run_e2e (test_tool_contract.TestVariantCaller) ... Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file core.py, line 153
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file core.py, line 205
ok
test_run_e2e (test_tool_contract.TestVariantCallerArrow) ... Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file core.py, line 153
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 880, in emit
    stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file core.py, line 205
ok

----------------------------------------------------------------------
Ran 5 tests in 7.553s

OK
```

I can only guess this is something going on in the pbcommand layer...

**Comment by dalexander** [comment]
I've disabled the unit test for now and I opened a more precise bug in BZ
